/**
 * Cartographie narrative du Verse Egor69 — salles disposées en anneau (~rayon 24 m).
 * Chaque entrée relie géographie 3D, promesse produit honnête et continuité avec l’interface 2D.
 */

export const WORLD_REALMS = [
  {
    slug: "accueil",
    label: "Sanctuaire d’accueil",
    shortHook: "L’entrée du pacte : présence, radar, vérité mesurable.",
    path: "/",
    color: "#34d399",
    pos: [0, 1.4, -26],
    atmosphere: "Brume ionisée au ras du sol, halo vert émeraude, silence ponctué de pulsations radar.",
    lore:
      "Ce portail ramène au hall principal : là où l’utilisateur comprend que Egor69 n’est pas une promesse creuse mais une géométrie de confiance — circulation des biens, des savoirs, et visibilité sur ce qui compte vraiment. C’est le seuil où l’on quitte le spectacle pour entrer dans le soin.",
    ritualHint: "Avant de traverser, respire une fois : nomme une intention honnête pour ta session (don, réparation, lecture).",
    connections: ["Hall des alliances", "Atlas vivant", "Grand Marché"],
    sensory: ["ozone doux", "grain de lumière sur la retine", "vibration basse comme un cœur au repos"],
    pledge: "Aucune métrique d’audience inventée : ce qui s’affiche doit être vérifiable ou qualifié comme projection.",
  },
  {
    slug: "market",
    label: "Grand Marché",
    shortHook: "Circulation tangible : offres, besoins, respect du vivant.",
    path: "/marketplace",
    color: "#38bdf8",
    pos: [18, 1.4, -18],
    atmosphere: "Néons froids sur métal brossé, foule fantomatique de flux API, bruine turquoise.",
    lore:
      "Le marché n’est pas une extraction : c’est une place où les objets reprennent des vies, où les prix sont autant des consentements que des équations. On y apprend la patience du troc, la clarté du descriptif, et la dignité du vendeur comme du donateur.",
    ritualHint: "Entre avec une liste courte : trois besoins réels, trois offres possibles — pas davantage.",
    connections: ["Sanctuaire d’accueil", "Place du réseau", "Hall des alliances"],
    sensory: ["reflets mobiles sur vitrine", "bourdonnement feutré", "odeur de carton sec et pluie"],
    pledge: "Les transactions suivent les règles publiées ; pas de piège tarifaire dans le narratif.",
  },
  {
    slug: "atlas",
    label: "Atlas vivant",
    shortHook: "Fiches sensibles : arts, savoirs, faune, flore, quêtes.",
    path: "/atlas",
    color: "#a78bfa",
    pos: [26, 1.4, 0],
    atmosphere: "Bibliothèque ouverte sous voûte céleste, catalogues suspendus, poussière de pollen numérique.",
    lore:
      "L’Atlas refuse le catalogue mort : chaque fiche respire, se fait corriger, accueille une sensation ou une critique. C’est la mémoire collective sans museification — les savoirs y sont traités comme des organismes, pas comme des tombes.",
    ritualHint: "Choisis une carte au hasard volontaire : lis-la à voix basse, puis ajoute une nuance personnelle.",
    connections: ["Spirale du génome", "Spires ésotériques", "Encyclopédie biblique"],
    sensory: ["parchemin tiède", "chant d’oiseau filtré", "texture rugueuse du savoir brut"],
    pledge: "Les contributions citoyennes sont signalées ; la communauté nourrit, ne remplace pas la validation expert.",
  },
  {
    slug: "bible",
    label: "Encyclopédie biblique",
    shortHook: "Textes, lieux, graphes : lecture stratifiée, pas simplisme.",
    path: "/encyclopedie-biblique",
    color: "#fbbf24",
    pos: [18, 1.4, 18],
    atmosphere: "Salle scripturaire : or liquide sur pierre froide, encens virtuel, silence vertigineux.",
    lore:
      "Ici la Bible devient navigable sans être aplatie : livres, personnages, lieux et thèmes s’entrelacent dans des cartes et timelines honnêtes sur ce qui est attesté, interpolé ou débattu. La foi et la critique peuvent cohabiter tant que la précision prime.",
    ritualHint: "Trace un lien entre deux entrées éloignées : note ce qui les unit sans forcer l’analogie.",
    connections: ["Panthéon 3D", "Tour numérologique", "Carte et graphe"],
    sensory: ["chant grégorien très lointain", "granité du parchemin", "lueur dorée sur les majuscules"],
    pledge: "Pas de fausse exhaustivité : les lacunes sont marquées ouvertement dans les fiches.",
  },
  {
    slug: "pantheon",
    label: "Panthéon 3D",
    shortHook: "Figures majeures rendues en volumes — contemplation architecturée.",
    path: "/pantheon-3d",
    color: "#f472b6",
    pos: [0, 1.4, 26],
    atmosphere: "Rotonde cosmique, statues semi-translucides, reverbs métalliques.",
    lore:
      "Le Panthéon matérialise des présences sans les figer dans le culte : chaque figure porte une étiquette de contexte. La beauté est invite à la lecture, pas substitut à la pensée.",
    ritualHint: "Tourne lentement autour d’un buste : observe l’ombre ; demande-toi ce qui manque au récit.",
    connections: ["Encyclopédie biblique", "Portail cosmique"],
    sensory: ["pas qui résonnent en octave", "brume rose basse", "froid du marbre simulé"],
    pledge: "Les rendus sont artistiques ; les attributions historiques restent sourcées hors fiction pure.",
  },
  {
    slug: "cosmic",
    label: "Portail cosmique",
    shortHook: "Faits cosmologiques & mystère mesuré — pas de mythologie marketing.",
    path: "/cosmic-portal",
    color: "#818cf8",
    pos: [-18, 1.4, 18],
    atmosphere: "Horizon courbe, plasma violet indigo, vents sidéraux sans bruit réel.",
    lore:
      "La cosmologie invoque l’humilité scientifique : distances, âges, vitesses — tout ce qui nous rappelle que la carte n’est pas le territoire. Le mystique suit, sans annuler les équations.",
    ritualHint: "Retiens trois chiffres et leur incertitude : la précision est déjà une spiritualité.",
    connections: ["Atlas vivant", "Tour numérologique"],
    sensory: ["vertige doux", "scintillement périphérique", "silence amplifié"],
    pledge: "Les ordres de grandeur sont issus de consensus scientifique actuel ; ils évoluent avec la recherche.",
  },
  {
    slug: "numerology",
    label: "Tour numérologique",
    shortHook: "Nombres comme langage — jeu conscient, pas oracle absolu.",
    path: "/numerology",
    color: "#fde047",
    pos: [-26, 1.4, 0],
    atmosphere: "Spirale dorée, prismes flottants, tintements de cristal harmoniques.",
    lore:
      "La numérologie ici est traitée comme psychologie symbolique et ludisme structuré : les profils se construisent à partir de données déclarées, sans prétention de destin fermé.",
    ritualHint: "Calcule ton chemin puis écris une contre-interprétation réaliste — garde les deux.",
    connections: ["Spires ésotériques", "Spirale du génome"],
    sensory: ["bourdonnement en quintes", "chaleur dans les paumes", "symétrie hypnotique"],
    pledge: "Les interprétations sont signalées comme symboliques ; aucune promesse médicale ou financière.",
  },
  {
    slug: "esoteric",
    label: "Spires ésotériques",
    shortHook: "Traditions : tarot, hermétisme, voies — contextualisées.",
    path: "/esotericism",
    color: "#22d3ee",
    pos: [-18, 1.4, -18],
    atmosphere: "Citadelle bleu glacier, flèches qui dansent sans vent, bibliothèques verticales.",
    lore:
      "Les spires accueillent les systèmes ésotériques comme anthropologie vivante : chaque pratique est présentée avec ses origines, ses risques et ses usages contemporains raisonnables.",
    ritualHint: "Choisis une tradition que tu ne pratiques pas : lis son article comme ethnologue, pas comme adepte.",
    connections: ["Atlas vivant", "Arène de magie"],
    sensory: ["encens froid", "glissement de drap", "écho court comme dans une coupelle"],
    pledge: "Pas de garantie surnaturelle : sensibilité culturelle et disclaimers clairs.",
  },
  {
    slug: "magic",
    label: "Arène de magie",
    shortHook: "Prestidigitation & démystification — plaisir sans mensonge.",
    path: "/magic-hub",
    color: "#c084fc",
    pos: [-10, 1.4, -24],
    atmosphere: "Scène circulaire, velours pourpre, étincelles contenues dans des sphères.",
    lore:
      "La magie de scène est un contrat de séduction honnête : le spectateur sait qu’il observe un artifice ; la plateforme conserve cette transparence en séparant illusion et affirmation factuelle.",
    ritualHint: "Après un tour, énonce à voix haute la limite de ce que tu sais encore ignorer.",
    connections: ["Spires ésotériques", "Grand Marché"],
    sensory: ["riflements de cartes", "odeur de cire", "rire nerveux contenu"],
    pledge: "Les tutoriels visent la sécurité ; pas de contenus dangereux présentés comme innocents.",
  },
  {
    slug: "genome",
    label: "Spirale du génome",
    shortHook: "Cartographie symbolique du vivant — précision biologique progressive.",
    path: "/genome",
    color: "#4ade80",
    pos: [10, 1.4, -24],
    atmosphere: "Laboratoire forestier, tubes luminescents, racines digitales.",
    lore:
      "Le volet ADN relie métabolique et mythique : les données biologiques sont présentées avec la gravité qu’elles méritent — aucune simplification insultante pour le vivant.",
    ritualHint: "Associe un trait humain à une fonction biologique puis à une responsabilité écologique.",
    connections: ["Atlas vivant", "Grand Marché"],
    sensory: ["ozone vert", "texture fibreuse", "battement synchronisé au pouls"],
    pledge: "Pas de diagnostic médical délivré par l’interface ; orientation vers professionnels réels.",
  },
  {
    slug: "feed",
    label: "Place du réseau",
    shortHook: "Flux communautaire — récit vivant, modéré par la lucidité.",
    path: "/feed",
    color: "#2dd4bf",
    pos: [24, 1.4, -10],
    atmosphere: "Agora liquide, conversations en spirale, lanternes suspendues.",
    lore:
      "Le réseau social interne est pensé comme une place publique : visibilité consentie, signalisation des excès, priorité aux récits vérifiables et aux gestes de réparation.",
    ritualHint: "Écris une nouvelle en cinq lignes à partir du dernier post lu — puis efface-la ou publie-la.",
    connections: ["Grand Marché", "Hall des alliances"],
    sensory: ["murmure polyphonique", "chaleur humaine simulée", "café tiède"],
    pledge: "Modération transparente sur les principes ; pas d’amplification algorithmique obscure.",
  },
  {
    slug: "pricing",
    label: "Hall des alliances",
    shortHook: "Tarifs clairs : alliance entre pairs, Stripe, aucune surprise narrative.",
    path: "/pricing",
    color: "#fb923c",
    pos: [-24, 1.4, 10],
    atmosphere: "Salle des pactes : tables en obsidienne, sceaux lumineux, contrastes orange profond.",
    lore:
      "Monétiser un espace spirituel et technique exige une liturgie contractuelle visible : paliers lisibles, ce qui est inclus, ce qui ne l’est pas, et une absence totale de chantage émotionnel aux faux chiffres.",
    ritualHint: "Compare deux paliers et note ce que tu refuserais de vendre même gratuitement.",
    connections: ["Sanctuaire d’accueil", "Place du réseau"],
    sensory: ["son de sceau sur cire", "odeur bois brûlé doux", "saturation visuelle maîtrisée"],
    pledge: "Paiement via processeur reconnu ; pas de stockage carte sur nos serveurs au-delà des flux décrits.",
  },

  /* — Anneau mythologique (constellation périphérique) : hub /mythologies + ancres #famille — */
  {
    slug: "myth-grecque",
    label: "Couronne de l’Olympe",
    shortHook: "Panorama hellénique : sources, tragédie, réceptions — sans orthodoxie imaginaire.",
    path: "/mythologies#grecque",
    color: "#93c5fd",
    pos: [39.2, 1.4, 6.8],
    atmosphere: "Marbre bleuté, foudre lointaine en halo, colonnes qui se dissolvent en données textuelles.",
    lore:
      "Ici commence la lecture responsable des mythes grecs : polyphonie des cités, jeux tragiques sur les normes, réécritures latines et modernes. Le portail renvoie vers des fiches contextualisées (sources antiques, débats savants, usages contemporains).",
    ritualHint: "Compare deux versions d’un même mythe (ex. création) et note ce qui change politiquement.",
    connections: ["Atlas vivant", "Encyclopédie biblique", "Hall des alliances"],
    sensory: ["ozone sec", " craquement de parchemin", "écho théâtral"],
    pledge: "Pas de pseudo-initiation : pédagogie, citations, prudence sur les anachronismes.",
  },
  {
    slug: "myth-egypt",
    label: "Barque du dieu-Rê",
    shortHook: "Nil, Duat, hiéroglyphes : strates théologiques et sensibilités vivantes.",
    path: "/mythologies#egyptienne",
    color: "#fcd34d",
    pos: [32.4, 1.4, 22.6],
    atmosphere: "Or en fusion sur basalte, reflets vert d’eau stagnante, scarabées lumineux en file.",
    lore:
      "Les mythes égyptiens se lisent en tableaux et processions autant qu’en récits linéaires. Ce portail souligne les syncrétismes dynastiques et la réception gréco-romaine sans réduire la complexité funéraire.",
    ritualHint: "Associe une scène du Livre des Morts à une question éthique contemporaine (mémoire, image, respect).",
    connections: ["Portail cosmique", "Atlas vivant"],
    sensory: ["résine chaude", "grain du sable", "chant nasal très lointain"],
    pledge: "Pas d’appropriation décorative des images sacrées : notices et contextes.",
  },
  {
    slug: "myth-celt",
    label: "Sid des géants",
    shortHook: "Îles, brumes, cycles — irlandais ≠ gallois ; druidisme antique fragmenté.",
    path: "/mythologies#celtique",
    color: "#6ee7b7",
    pos: [14.2, 1.4, 36.4],
    atmosphere: "Tourbe luminescente, menhirs polygonaux, corbeaux en orbite lente.",
    lore:
      "Le panneau distingue sources médiévales chrétiennes et matériaux plus anciens hypothétiques. Les héros (Cú Chulainn, figures du Mabinogion) sont lus comme littérature et histoire culturelle.",
    ritualHint: "Trace une carte mentale : quelle île, quel manuscrit, quel siècle ?",
    connections: ["Spires ésotériques", "Atlas vivant"],
    sensory: ["pluie fine", "fer humide", "harpe distante"],
    pledge: "Refus des « druides commerciaux » sans sources ; honnêteté sur les lacunes.",
  },
  {
    slug: "myth-nord",
    label: "Anneau du Midgard",
    shortHook: "Eddas, runes, archéologie — Ragnarök comme horizon narratif, pas manifeste.",
    path: "/mythologies#nordique",
    color: "#7dd3fc",
    pos: [-8.6, 1.4, 38.1],
    atmosphere: "Granit noir, aurore vert lichen, braises sous vent du large.",
    lore:
      "Le nord germanique offre une cosmologie en anneaux et une poétique du don fatal. Les sources sont tardives et islandaises : les interprétations politiques du XIXe–XXe siècle sont signalées.",
    ritualHint: "Choisis un poème eddique : repère où Snorri commente vs rapporte.",
    connections: ["Portail cosmique", "Arène de magie"],
    sensory: ["sel sur la langue", "bois résineux brûlé", "vent sans cimes"],
    pledge: "Distinction stricte entre reconstitution historique et usages idéologiques abusifs.",
  },
  {
    slug: "myth-meso",
    label: "Septuple vent",
    shortHook: "Sumér, Babylone, Assyrie : tablettes, versions plurielles, déluge comparé.",
    path: "/mythologies#mesopotamienne",
    color: "#c4b5fd",
    pos: [-28.0, 1.4, 27.5],
    atmosphere: "Argile séchée en spirales, constellations gravées, bitume tiède.",
    lore:
      "Les mythes mésopotamiens irriguent les imaginaires proche-orientaux et certaines strates bibliques : ici, comparaison documentée, pas chasse aux « preuves » simplistes.",
    ritualHint: "Lis un passage d’Enuma Elish à voix basse, puis résume l’enjeu politique babylonien.",
    connections: ["Encyclopédie biblique", "Atlas vivant"],
    sensory: ["poussière minérale", "empreinte du stylet", "silence archivistique"],
    pledge: "Traductions académiques prioritaires ; pas de pseudo-décryptage cunéiforme.",
  },
  {
    slug: "myth-india",
    label: "Chakra du char",
    shortHook: "Véda, épopées, Purāṇa : traditions vivantes, bhakti, responsabilité de lecture.",
    path: "/mythologies#indienne",
    color: "#fb7185",
    pos: [-39.0, 1.4, 4.5],
    atmosphere: "Encens cardamome, bronze poli, roue qui scintille sans tourner complètement.",
    lore:
      "Les récits indiens se déclinent en langues et en régimes de vérité multiples. Le portail insiste sur l’éthique de citation et le respect des pratiquants contemporains.",
    ritualHint: "Note une scène du Mahābhārata comme dilemme moral, pas comme spectacle de super-pouvoirs.",
    connections: ["Spires ésotériques", "Tour numérologique"],
    sensory: ["clochettes lointaines", "chaleur du métal au soleil", "tessiture vocale"],
    pledge: "Pas d’extractivisme spirituel ; contextualisation et crédits aux traditions vivantes.",
  },
  {
    slug: "myth-japan",
    label: "Îles des kami",
    shortHook: "Kojiki, Nihon shoki, shintō : seuils, purifications, yōkai pop.",
    path: "/mythologies#japonaise",
    color: "#f9a8d4",
    pos: [-33.6, 1.4, -18.2],
    atmosphere: "Torii flottant en verre fumé, cerisiers en pixels, pluie fine verticale.",
    lore:
      "La mythologie impériale et les cultes locaux cohabitent avec des réinventions médiatiques. Le module distingue sources classiques, bouddhisme syncrétique et culture populaire.",
    ritualHint: "Identifie un kami local (lieu réel) et compare avec sa version médiatique.",
    connections: ["Portail cosmique", "Atlas vivant"],
    sensory: ["tatami froid", "goutte suspendue", "battement d’aile d’insecte"],
    pledge: "Respect des sites et des pratiquants ; pas d’exotisme décoratif.",
  },
  {
    slug: "myth-china",
    label: "Ciel réparé",
    shortHook: "Classiques, taoïsme, bouddhisme, pantéons populaires — strates à déplier.",
    path: "/mythologies#chinoise",
    color: "#f87171",
    pos: [-16.8, 1.4, -35.4],
    atmosphere: "Jade brumeux, dragons serpentant comme rivières de données, tambours de bronze.",
    lore:
      "Nuwa, Fuxi, Pan Gu et les hiérarchies taoïstes ultérieures : le portail propose une lecture en couches (classique, populaire, moderne) sans réduction « mystique orientale ».",
    ritualHint: "Associe un mythe de création à une institution historique donnée (cour, temple, roman).",
    connections: ["Atlas vivant", "Spires ésotériques"],
    sensory: ["encens sandalwood", "brosse sur encre", "vent dans bambous"],
    pledge: "Éviter les clichés New Age ; contextualiser les traductions.",
  },
  {
    slug: "myth-rome",
    label: "Aigle augural",
    shortHook: "Religion civique, interpretatio, apothéoses — Empire comme rituel.",
    path: "/mythologies#romaine",
    color: "#fdba74",
    pos: [6.2, 1.4, -38.6],
    atmosphere: "Marbre travertin, pourpre en lambeaux, fumée d’encens civique.",
    lore:
      "Les mythes fondateurs (Énée, Romulus) soutiennent des programmes politiques. Les cultes importés (Isis, Cybele, Mithra) montrent une géographie religieuse de l’empire.",
    ritualHint: "Compare Jupiter Capitolinus et Zeus Olympien : que change le cadre romain ?",
    connections: ["Grand Marché", "Hall des alliances"],
    sensory: ["fer chaud", "pas lourds", "odeur de pluie sur pierre"],
    pledge: "Histoire des religions, pas propagande impériale moderne.",
  },
  {
    slug: "myth-yoruba",
    label: "Marché des Ifá",
    shortHook: "Òrìṣà, Ifá, diaspora : respect, contextualisation, anti-extractivisme.",
    path: "/mythologies#yoruba",
    color: "#a3e635",
    pos: [28.5, 1.4, -26.8],
    atmosphere: "Tissus indigo, tambours parlants, motifs géométriques en suspension.",
    lore:
      "Les traditions Yorùbá et leurs syncrétismes atlantiques sont vivantes. Le portail met l’accent sur les voix autochtones, la divination comme poésie morale et les risques du commerce global des symboles.",
    ritualHint: "Écoute un enregistrement liturgique (si droits clairs) et note structure rythmique + sens public.",
    connections: ["Spires ésotériques", "Place du réseau"],
    sensory: ["poudre de bois", "chaleur humaine", "frémissement de peau"],
    pledge: "Pas de vente de « packs initiatiques » : signaler les dérives commerciales.",
  },
  {
    slug: "myth-poly",
    label: "Navigation Maui",
    shortHook: "Triangle polynésien : pluralité linguistique, mer, tapu.",
    path: "/mythologies#polynesienne",
    color: "#22d3ee",
    pos: [38.0, 1.4, -12.4],
    atmosphere: "Lagons en gradient, constellations basses, pirogues fantômes en filigrane.",
    lore:
      "Les mythes polynésiens varient par île ; Maui change de personnalité. Le portail refuse la fusion « décor tiki » et oriente vers anthropologies et revitalisations contemporaines.",
    ritualHint: "Choisis deux îles : compare deux versions du même motif (Maui ou création).",
    connections: ["Portail cosmique", "Atlas vivant"],
    sensory: ["sel en cristaux", "vent alizé", "corde tendue"],
    pledge: "Crédit aux sources autochtones et aux langues locales.",
  },
  {
    slug: "myth-americas",
    label: "Turtle Island",
    shortHook: "Nations des Amériques : pluralité absolue, tricksters, revitalisations.",
    path: "/mythologies#amerindigenous",
    color: "#4ade80",
    pos: [20.6, 1.4, 32.0],
    atmosphere: "Forêts mêlées de brouillard et de constellations animales, tambours lointains.",
    lore:
      "Aucun panthéon unique : le portail pointe vers une synthèse comparative honnête, rappelle les génocides et les politiques de revitalisation, et refuse le chamanisme extractif.",
    ritualHint: "Sélectionne une nation précise (territoire, langue) avant de lire un récit.",
    connections: ["Atlas vivant", "Sanctuaire d’accueil"],
    sensory: ["mousse humide", "feuilles bruissantes", "silence respectueux"],
    pledge: "Priorité aux sources autochtones ; pas de playthrough colonial.",
  },

  /* — Anneau bien-être (périphérie R≈50) : hub /bien-etre-lexique + ancres #famille — */
  {
    slug: "well-herbe",
    label: "Serre des monographies",
    shortHook: "Phytothérapie : titrages, interactions, identifications — sans « naturel = innocent ».",
    path: "/bien-etre-lexique#herboristerie",
    color: "#4ade80",
    pos: [25.0, 1.4, 43.3],
    atmosphere: "Verre dépoli, étiquettes botaniques suspendues, résine de pin et mortier en ombre chinoise.",
    lore:
      "L’herboristerie raisonnée confronte traditions et monographies modernes. Ce portail rappelle que les plantes sont des molécules : doses, solvants, contre-indications et interactions comptent autant que le romantisme des récoltes.",
    ritualHint: "Choisis une plante que tu crois connaître : lis deux monographies contradictoires et note ce qui diverge.",
    connections: ["Atlas vivant", "Atelier du terrain"],
    sensory: ["feuilles sèches froissées", "alcool doux", "papier granuleux"],
    pledge: "Pas de prescription : pédagogie, prudence, orientation médicale si symptômes.",
  },
  {
    slug: "well-naturo",
    label: "Atelier du terrain",
    shortHook: "Naturopathie : hygiènes de vie, cadres légaux variables, pas de retard diagnostique.",
    path: "/bien-etre-lexique#naturopathie",
    color: "#34d399",
    pos: [43.3, 1.4, 25.0],
    atmosphere: "Lumière latérale sur bois clair, carnets ouverts, balance à grains fantôme.",
    lore:
      "La naturopathie recoupe nutrition, mouvement, sommeil et parfois phytothérapie selon formations. Ici, on insiste sur la diversité des titres et sur la frontière avec le diagnostic médical réservé.",
    ritualHint: "Écris trois habitudes réelles (sommeil, marche, repas) avant d’ajouter un produit.",
    connections: ["Serre des monographies", "Place du réseau"],
    sensory: ["lin frais", "herbe coupée", "page qui tourne"],
    pledge: "Refus des promesses de guérison unique ; transparence sur limites légales.",
  },
  {
    slug: "well-massage",
    label: "Salle des paumes tempérées",
    shortHook: "Massage bien-être : consentement, pression, contre-indications — spa ≠ kiné.",
    path: "/bien-etre-lexique#massages",
    color: "#2dd4bf",
    pos: [50.0, 1.4, 0.0],
    atmosphere: "Huiles tièdes, brume légère, basses fréquences feutrées, draps en suspension lente.",
    lore:
      "Le massage relaxe et modifie la perception douloureuse bénigne ; il ne remplace pas l’avis médical en cas de signaux d’alerte. Les protocoles oncologiques et vasculaires demandent une coordination explicite.",
    ritualHint: "Pratique une minute de respiration avant d’imposer une pression — même à soi-même.",
    connections: ["Place du réseau", "Spires ésotériques"],
    sensory: ["chaleur palmaire", "odeur d’amande douce", "musique étouffée"],
    pledge: "Consentement clair ; pas de « libération de toxines » sans preuve.",
  },
  {
    slug: "well-aroma",
    label: "Distillerie des brumes",
    shortHook: "HE : dilution, diffusion courte, populations sensibles — ingestion amateur interdite.",
    path: "/bien-etre-lexique#aromatherapie",
    color: "#5eead4",
    pos: [43.3, 1.4, -25.0],
    atmosphere: "Alambics en verre, halos bleutés, compte-gouttes suspendus comme pendules.",
    lore:
      "Les huiles essentielles concentrent des toxicités réelles. Le portail relie plaisir olfactif, données toxicologiques et respect des chats, enfants et grossesses.",
    ritualHint: "Mesure une dilution test sur une petite zone ; attends 24 h avant d’étendre.",
    connections: ["Serre des monographies", "Salle des paumes tempérées"],
    sensory: ["camphre lointain", "vapeur fraîche", "picotement nasal"],
    pledge: "Pas de cocktail interne maison ; signaler risques hépatiques et neurologiques.",
  },
  {
    slug: "well-sophro",
    label: "Salle des sept respirations",
    shortHook: "Sophrologie : relaxation structurée, activation positive — repérage psychiatrique.",
    path: "/bien-etre-lexique#sophrologie",
    color: "#6ee7b7",
    pos: [25.0, 1.4, -43.3],
    atmosphere: "Gradins doux, miroirs dépolis, métronome humain à peine audible.",
    lore:
      "La sophrologie hybride relaxation et visualisation. Utile au stress modéré ; le portail rappelle l’orientation vers soins spécialisés si décompensation.",
    ritualHint: "Enregistre une séance courte et note où l’attention se perd — sans juger.",
    connections: ["Portail cosmique", "Pharmacie des dilutions"],
    sensory: ["tissu sur la peau", "air neutre", "silence structuré"],
    pledge: "Pas de miracle sur traumas non stabilisés.",
  },
  {
    slug: "well-homeo",
    label: "Pharmacie des dilutions",
    shortHook: "Homéopathie : débat public de preuves — risque majeur de substitution.",
    path: "/bien-etre-lexique#homeopathie",
    color: "#a7f3d0",
    pos: [0.0, 1.4, -50.0],
    atmosphere: "Étagères blanches infinies, granules comme poussière de lune, silence administratif.",
    lore:
      "Ce portail expose sans ambages les positions des autorités de santé et la littérature conflictuelle. L’enjeu éthique est la non-substitution aux traitements dont l’efficacité est établie.",
    ritualHint: "Compare une indication populaire à une revue systématique récente — note l’écart.",
    connections: ["Spires ésotériques", "Atlas vivant"],
    sensory: ["sucré léger", "plastique propre", "feuille de consentement"],
    pledge: "Transparence sur incertitudes ; pas de dénigration ad hominem des usagers.",
  },
  {
    slug: "well-holistique",
    label: "Toile des contextes",
    shortHook: "Holistique : biopsychosocial sérieux vs marketing de « tout connecté ».",
    path: "/bien-etre-lexique#approche-holistique",
    color: "#86efac",
    pos: [-25.0, 1.4, -43.3],
    atmosphere: "Fils lumineux entre silhouettes, cartes sociales et écosystèmes en transparence.",
    lore:
      "L’approche holistique digne de ce nom intègre sommeil, travail, relations, nutrition et soins médicaux quand nécessaire. Elle refuse la culpabilisation magique du patient.",
    ritualHint: "Dessine trois cercles : corps, relations, environnement — place un symptôme récent.",
    connections: ["Hall des alliances", "Laboratoire des doses"],
    sensory: ["laine tiède", "graphite", "bruit de ville lointaine"],
    pledge: "Pas de promesse de guérison par la seule conscience.",
  },
  {
    slug: "well-nutri",
    label: "Laboratoire des doses",
    shortHook: "Micronutrition : carences réelles vs packs ; interactions thyroïde, sang, foie.",
    path: "/bien-etre-lexique#micronutrition",
    color: "#bef264",
    pos: [-43.3, 1.4, -25.0],
    atmosphere: "Compte-gouttes métalliques, tubes étiquetés, tableaux periodiques en surbrillance douce.",
    lore:
      "Les compléments peuvent aider quand le besoin est documenté ; le portail combat les méga-doses fashion et rappelle les interactions critiques.",
    ritualHint: "Liste les médicaments actuels avant tout nouvel apport — même « naturel ».",
    connections: ["Grand Marché", "Sources chaud-froid"],
    sensory: ["poudre sèche", "ozone léger", "clic de cap"],
    pledge: "Éviter les allégations miraculeuses non autorisées.",
  },
  {
    slug: "well-hydro",
    label: "Sources chaud-froid",
    shortHook: "Thermalisme médical vs spa ; bains nordiques : cœur et pression.",
    path: "/bien-etre-lexique#hydrothermalisme",
    color: "#67e8f9",
    pos: [-50.0, 1.4, 0.0],
    atmosphere: "Vapeur et glace en balance, pierre basalte, chronomètres géants au mur.",
    lore:
      "Les cures thermales relèvent d’indications et de contre-indications nationales. Les spas mélangent plaisir et récupération ; le portail refuse l’amalgame des preuves.",
    ritualHint: "Si tu alternes chaud/froid, chronomètre et hydrate — arrête si vertige.",
    connections: ["Salle des paumes tempérées", "Sanctuaire d’accueil"],
    sensory: ["chlore doux", "choc thermique", "eau qui ruisselle"],
    pledge: "Pas de diagnostic par la température de l’eau.",
  },
  {
    slug: "well-psychocorp",
    label: "Salle des seuils",
    shortHook: "Psychocorporel : trauma-informed, consentement, supervision — pas performance.",
    path: "/bien-etre-lexique#therapies-psychocorporelles",
    color: "#7dd3fc",
    pos: [-43.3, 1.4, 25.0],
    atmosphere: "Coussins fermes, cordes symboliques, lumière latérale basse, horloge discrète.",
    lore:
      "Les thérapies qui lient corps et émotion exigent cadre déontologique. Le portail met en garde contre les techniques invasives et les rôles flous entre coaching et psychothérapie.",
    ritualHint: "Écris une phrase de consentement que tu voudrais entendre avant un toucher thérapeutique.",
    connections: ["Spires ésotériques", "Salle des sept respirations"],
    sensory: ["tissu dense", "respiration synchronisée", "pause silencieuse"],
    pledge: "Priorité à la sécurité psychique ; orientation si crises.",
  },
  {
    slug: "well-acu",
    label: "Salle des aiguilles calmes",
    shortHook: "MTC / acupuncture : essais cliniques sélectifs, cadres d’exercice, sécurité.",
    path: "/bien-etre-lexique#acupuncture-tcm",
    color: "#93c5fd",
    pos: [-25.0, 1.4, 43.3],
    atmosphere: "Bambou, lin blanc, modèles anatomiques translucides, bruit d’emballage stérile.",
    lore:
      "L’acupuncture est étudiée pour certaines nausées et douleurs chroniques ; les explications classiques cohabitent avec la neurophysiologie. Le portail refuse le folklore raciste ou réducteur.",
    ritualHint: "Identifie une indication avec revue récente — note la taille d’effet prudente.",
    connections: ["Atlas vivant", "Toile des contextes"],
    sensory: ["odeur d’alcool doux", "contact ponctuel", "clochettes lointaines"],
    pledge: "Respect du cadre légal local ; aiguilles stériles.",
  },
  {
    slug: "well-ayur",
    label: "Cour des trois saisons",
    shortHook: "Ayurveda : institutions vs export ; qualité des préparations, interactions.",
    path: "/bien-etre-lexique#ayurveda",
    color: "#fcd34d",
    pos: [0.0, 1.4, 50.0],
    atmosphere: "Bronze, turmeric en suspension lumineuse, manuscrits enluminés en boucle.",
    lore:
      "La tradition ayurvédique est riche et institutionnelle sur le sous-continent ; à l’international, qualité et sécurité varient. Le portail cite risques de contaminants et besoin de coordination médicale.",
    ritualHint: "Compare une pratique clinique en Inde à une offre spa occidentale : liste les écarts de garde-fous.",
    connections: ["Atlas vivant", "Spires ésotériques"],
    sensory: ["épices chaudes", "huile sur pierre", "ventilateur lent"],
    pledge: "Respect culturel ; vigilance sur produits importés non contrôlés.",
  },

  /* — Anneau divinatoire (R≈54) : hub /arts-divinatoires-lexique + ancres #famille — */
  {
    slug: "div-tarot",
    label: "Galerie des lames",
    shortHook: "Tarot : langage d’images, cadre éthique — pas de sentence sur une personne.",
    path: "/arts-divinatoires-lexique#tarot",
    color: "#a78bfa",
    pos: [20.7, 1.4, 49.9],
    atmosphere: "Velours pourpre, reflets sur vernis, silence entre deux battements de cartes.",
    lore:
      "Le portail relie tirage ludique, journal créatif et pratiques encadrées. Il refuse la malédiction commerciale et le chantage à la peur.",
    ritualHint: "Formule une question fermée puis ouvre — note ce que la question présuppose déjà.",
    connections: ["Spires ésotériques", "Salle des sept respirations"],
    sensory: ["carton neuf", "cire tiède", "page qui frémit"],
    pledge: "Fiction et introspection oui ; autorité abusive non.",
  },
  {
    slug: "div-astro-nat",
    label: "Sphère éphéméride",
    shortHook: "Astrologie natale : calculs sérieux, promesses mesurées, pas de fatalisme.",
    path: "/arts-divinatoires-lexique#astrologie-natale",
    color: "#818cf8",
    pos: [49.9, 1.4, 20.7],
    atmosphere: "Globe projeté, grilles de maisons en filigrane, café froid sur console.",
    lore:
      "Ici convergent histoire des techniques et honnêteté statistique sur les tests « signe ». Le portail distingue culture, outil et prétention.",
    ritualHint: "Compare deux systèmes de maisons sur le même thème : note ce qui change sans changer le ciel.",
    connections: ["Tour numérologique", "Atlas vivant"],
    sensory: ["plastique clavier", "lueur bleue", "tique d’horloge"],
    pledge: "Pas de discrimination embauche ou couple fondée sur carte.",
  },
  {
    slug: "div-astro-cn",
    label: "Palais du sexagénaire",
    shortHook: "Astrologie chinoise : piliers, cycles, respect des pratiquants — pas zodiaque réducteur.",
    path: "/arts-divinatoires-lexique#astrologie-chinoise",
    color: "#f472b6",
    pos: [49.9, 1.4, -20.7],
    atmosphere: "Rouleaux rouges, encres or, compteurs de branches qui cliquent doucement.",
    lore:
      "Le portail met en garde contre la fusion marketing « animal » et l’analyse fine des quatre piliers ; il rappelle les contextes diasporiques.",
    ritualHint: "Traduis une formule calendaire sans la transformer en slogan occidental.",
    connections: ["Ciel réparé", "Salle des aiguilles calmes"],
    sensory: ["bambou sec", "cire d’étanchéité", "vent du couloir"],
    pledge: "Pas d’extractivisme spirituel.",
  },
  {
    slug: "div-yijing",
    label: "Cour des hexagrammes",
    shortHook: "Yi Jing : classique, tirage, philosophie — pas table de décision judiciaire.",
    path: "/arts-divinatoires-lexique#yi-jing",
    color: "#fbbf24",
    pos: [20.7, 1.4, -49.9],
    atmosphere: "Sable fin, baguettes alignées, voix basse lisant les ailes du classique.",
    lore:
      "Le portail honore le Zhouyi comme texte et pratique ritualisée ; il refuse la vente de certitude absolue.",
    ritualHint: "Note une ligne mobile comme question morale, pas comme ordre.",
    connections: ["Spires ésotériques", "Atlas vivant"],
    sensory: ["odeur de vieux papier", "grain de sable", "silence après le jet"],
    pledge: "Transparence sur RNG ou tirage manuel.",
  },
  {
    slug: "div-runes",
    label: "Hall des inscriptions",
    shortHook: "Runes : philologie d’abord, tirage moderne honnête, vigilance politique.",
    path: "/arts-divinatoires-lexique#runes-nordiques",
    color: "#94a3b8",
    pos: [-20.7, 1.4, -49.9],
    atmosphere: "Pierre froide, copeaux de bois, reproductions de bracteates sous verre.",
    lore:
      "Le portail relie musée et atelier : les runes ne sont pas un uniforme idéologique.",
    ritualHint: "Choisis une inscription réelle (lieu, siècle) avant d’inventer une « sagesse viking ».",
    connections: ["Anneau du Midgard", "Spires ésotériques"],
    sensory: ["acier froid", "résine", "pas lourds"],
    pledge: "Signaler détournements extrémistes.",
  },
  {
    slug: "div-geom",
    label: "Cour du sable fin",
    shortHook: "Géomancie : figures, maisons, traditions croisées — respect des corpus.",
    path: "/arts-divinatoires-lexique#geomancie",
    color: "#cbd5e1",
    pos: [-49.9, 1.4, -20.7],
    atmosphere: "Table basse carrée, sablier, traits tracés puis effacés dans un bac.",
    lore:
      "Le portail refuse la fusion paresseuse des géomancies africaines et latines ; il invite à la lecture comparée.",
    ritualHint: "Trace une figure puis nomme sa source culturelle précise.",
    connections: ["Marché des Ifá", "Atlas vivant"],
    sensory: ["sable qui coule", "bois lisse", "main qui effleure"],
    pledge: "Pas de promesse de futur chiffré.",
  },
  {
    slug: "div-carto",
    label: "Salle du tap vert",
    shortHook: "Cartomancie populaire : conventions locales, prix clairs, pas de maléfice à payer.",
    path: "/arts-divinatoires-lexique#cartomancie",
    color: "#34d399",
    pos: [-49.9, 1.4, 20.7],
    atmosphere: "Néons tamisés, son de cartes battues, horloge murale visible.",
    lore:
      "Le portail célèbre le jeu de salon et la parole modeste ; il dénonce les arnaques à la peur.",
    ritualHint: "Fixe une durée et un prix avant la première coupe.",
    connections: ["Grand Marché", "Spires ésotériques"],
    sensory: ["feutre humide", "rire étouffé", "glissière de jeton"],
    pledge: "Mineurs protégés ; publicité honnête.",
  },
  {
    slug: "div-oniro",
    label: "Chambre de la lucarne",
    shortHook: "Rêves : journal, clinique, neurosciences — pas preuve seule d’un crime ou d’un destin.",
    path: "/arts-divinatoires-lexique#oniromancie",
    color: "#67e8f9",
    pos: [-20.7, 1.4, 49.9],
    atmosphere: "Bleu nuit, carnet ouvert, réveil reculé, bruit de plume.",
    lore:
      "Le portail relie onirocritique historique et sommeil médical ; il refuse la culpabilisation par symbole.",
    ritualHint: "Écris le rêve brut avant toute grille de symboles.",
    connections: ["Spires ésotériques", "Toile des contextes"],
    sensory: ["drap frais", "encre", "première lumière du jour"],
    pledge: "Orientation trauma si répétition intrusive.",
  },
];

export const REALM_COUNT = WORLD_REALMS.length;
